version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=entag
      - DB_USER=entaguser
      - DB_PASSWORD=SEuELw3c7bybuoOcc14NpeAXUj5uanCt
      - DB_HOST=dpg-cnd1cjf109ks738qih8g-a.oregon-postgres.render.com
      - DB_PORT=5432
      - SECRET_KEY=RUIUIBFI)*(&09w983)*(&^knkjbiBIBibkbibi_09jfnwegwr
      - DEPLOYMENT_RENDER=False
