# Generated by Django 5.0.2 on 2024-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_artistreview_gig_historicalartistreview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gig",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgig",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
