# Generated by Django 5.0.2 on 2024-08-09 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_gig_status_alter_historicalgig_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="reason_for_rejection",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgig",
            name="reason_for_rejection",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmessage",
            name="gig",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer.gig",
            ),
        ),
        migrations.AddField(
            model_name="historicalmessage",
            name="is_counter_offer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="gig",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gig_messages",
                to="customer.gig",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_counter_offer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gig",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("counter_offer", "Counter Offer"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgig",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("counter_offer", "Counter Offer"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
