# Generated by Django 5.0.2 on 2024-08-09 23:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_gig_reason_for_rejection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistapplication",
            name="sample_songs",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="historicalartistapplication",
            name="sample_songs",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
    ]
