# Generated by Django 5.0.2 on 2024-03-13 11:01

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="co_author",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(location="uploads"),
                upload_to="blog_images/",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_anonymous",
            field=models.BooleanField(default=True),
        ),
    ]
