# Generated by Django 5.0.2 on 2024-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="number_of_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="ranking",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="total_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalartistprofile",
            name="number_of_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalartistprofile",
            name="ranking",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalartistprofile",
            name="total_rating",
            field=models.IntegerField(default=0),
        ),
    ]
