# Generated by Django 5.0.2 on 2024-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_artistprofile_number_of_ratings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistprofile",
            name="price_per_service",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalartistprofile",
            name="price_per_service",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
