# Generated by Django 5.0.2 on 2024-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_artistprofile_price_per_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="skilled_profession",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="historicalartistprofile",
            name="skilled_profession",
            field=models.CharField(default="", max_length=256),
        ),
    ]
