# Generated by Django 5.0.2 on 2024-08-09 23:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_historicaluserverificationrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="samples",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="historicaladminprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="historicalartistprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="historicalartistprofile",
            name="samples",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomerprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
