# Generated by Django 5.0.2 on 2024-08-09 23:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="proof",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldispute",
            name="proof",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
    ]
